### ISSUE TITLE
issue hosting on github

### ISSUE THREAD

**Issue by rlzijdeman** [mgskjaeveland/sgvizler#66]
Hi, I've followed the example file from your webpage resulting the in the attached file (remove .txt extension). Locally the file works perfect: after a few seconds the image appears. However, when pushing the file to github, the image does not appear. Any idea why that might be the case? See: https://rlzijdeman.github.io and https://github.com/rlzijdeman/rlzijdeman.github.io

Best wishes, Richard
[index.html.txt](https://github.com/mgskjaeveland/sgvizler/files/501395/index.html.txt)

**Comment by mgskjaeveland** [comment]
If I open the page in firefox with firebug, http://getfirebug.com/, 
enabled, I get the following error messages in the console output:

   Blocked loading mixed active content 
"http://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.js"
   Blocked loading mixed active content 
"http://mgskjaeveland.github.io/sgvizler/v/0.6/sgvizler.js"
   Blocked loading mixed active content 
"http://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.js"
   Blocked loading mixed active content 
"http://mgskjaeveland.github.io/sgvizler/v/0.6/sgvizler.js"

Seems that all the javascripts are blocked by the server.
