### ISSUE TITLE
Refactoring...

### ISSUE THREAD

**Issue by BorderCloud** [mgskjaeveland/sgvizler#70]
Hello

I started to refactor because I need to disable Google sometimes and to add the lib 3Djs and DataTable.
For the moment, I moved the code for Google in another folder.

You can see the first  result here  and a first example with this version
https://github.com/BorderCloud/sgvizler/blob/master/test/bordercloud.html
https://github.com/BorderCloud/sgvizler/blob/master/src/modules/bordercloud/visualization/TableExtension.js

I don't know if you want to keep your class datatable in the core because it's different for each lib of charts ? 
and so, I don't know if you want to keep Google in the core of Sgvizler ?

Thanks
Bye
Karima

**Comment by BorderCloud** [comment]
I think also rebuild the code respecting ECMAScript 2015 standards in order to generate JSDOC directly (example and tutorial)...

**Comment by mgskjaeveland** [comment]
The links you list give a 404-error, have you decided not to refactor?

I have no objections of loosing up no the tight relation to the Google libraries. 
It would be great if you would update the code to newer standards.

**Comment by BorderCloud** [comment]
Finally, I rewrite the project in ecma2016. In 2 or 3 day, I propose Sgvizler2... 
Say me, if there is a problem with this name.

I can stay compatible with your specification but with coverage, testunit, JDoc, etc... I thinks, It's necessary to accelerate this project...

**Comment by BorderCloud** [comment]
Hi
Sorry, I am late. I cannot generate the JSDoc for the moment :(
https://github.com/BorderCloud/sgvizler2

But, you can see the first version, here : https://bordercloud.github.io/sgvizler2/tutorial-A_Editor.html
The project can generate this form and the doc of each new chart :
https://bordercloud.github.io/sgvizler2/tutorial-sgvizler_visualization_Table.html

I will transfer the old charts progressively the next week.

Tell me what you think about it.

**Comment by mgskjaeveland** [comment]
Looks good!
