### ISSUE TITLE
Remove base URL in Tables (Broken hrefs)

### ISSUE THREAD

**Issue by freaksN** [mgskjaeveland/sgvizler#73]
When you run the following code
`//HTML`:
`<div id="searchResults"></div>`

`//JS`
`//Initialize sgvizler Query`
`var A = new sgvizler.Query();`

`A.query(" PREFIX dc: <http://purl.org/dc/terms/> PREFIX am: <http://data.linkedmdb.org/resource/movie/actor_name> SELECT ?a ?b WHERE { ?b am: 'Christian Bale' . ?b am: ?a. } ")`
  `.endpointURL("http://data.linkedmdb.org/sparql")`
  `.endpointOutputFormat("jsonp")`
 ` .chartFunction("sgvizler.visualization.Table")`
  `.draw("searchResults");`

### Actual behaviour: clicking on the links loads base URL + actual link, which results in broken link

Link to stackoverflow with `code snippet`: https://stackoverflow.com/questions/49498522/sgvizler-remove-base-url?noredirect=1#comment86017630_49498522

**Comment by freaksN** [comment]
Has anybody encountered the same problem and has possibly found some fix for it ?

**Comment by BorderCloud** [comment]
I tested with Sgvizler2. I have an error message in the javascript log :

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://bordercloud.github.io' is therefore not allowed access

You need to configure your SPARQL service to allow another origin and it will work with Sgvizler.

May be, your problem is in relation with the configuration of your Jetty server : 
https://stackoverflow.com/questions/16037558/how-to-add-access-control-allow-origin-to-jetty-server

**Comment by freaksN** [comment]
@BorderCloud I'm not quite sure that this is the cause of the broken hrefs. The problem you're referring to actually has an easy fix. The workaround is just to change the output format.

**Comment by freaksN** [comment]
@mgskjaeveland Any thoughts ? Do you have maybe some idea how can I fix the broken links?

**Comment by freaksN** [comment]
Until now I've been adding sgvizler through:
`<script  src="https://mgskjaeveland.github.io/sgvizler/v/0.6/sgvizler.js"></script>`

But this isn't the version that has the last update
`https://github.com/mgskjaeveland/sgvizler/commit/bc31a66c0a7d014a5d2d2c54aed84022169419f1`

Is there a online version with the last update somewhere ?

**Comment by mgskjaeveland** [comment]
> Is there a online version with the last update somewhere ?

Yes, here: https://mgskjaeveland.github.io/sgvizler/v/0.7/sgvizler.js
Does that work?

**Comment by freaksN** [comment]
> Is there a online version with the last update somewhere ?

>Yes, here: https://mgskjaeveland.github.io/sgvizler/v/0.7/sgvizler.js
Does that work?

Yes! Thank you!
