### ISSUE TITLE
Run time SPARQL Query

### ISSUE THREAD

**Issue by Gautamshahi** [mgskjaeveland/sgvizler#81]
Hello,

I am using the library by writing the SPARQL query explicitly, is there any implementation or way through which we can pass the SPARQL in an automated way. 

By this, we can show different result by changing the SPARQL Query.

**Comment by mgskjaeveland** [comment]
No sorry, there is no particular support for this. Perhaps https://bordercloud.github.io/sgvizler2/ and https://bordercloud.github.io/sgvizler2/tutorial-A_Editor.html is what you want?
