### ISSUE TITLE
Sgvizler 3.0

### ISSUE THREAD

**Issue by jaygray0919** [mgskjaeveland/sgvizler#83]
We have experimented with many Sgvizler alternatives for visualizing SPARQL queries.
None is as flexible or comprehensive as Sgvizler 2.0.
But Sgvizler 2.0 needs a refresh to work coorectly in an HTTPS world.
Hopefully, you'll consider upgrading Sgvizler 2.0 to Sgvizler 3.0 and enhance its utility with support for new Google visualization equivalents.
/jay gray

**Comment by BorderCloud** [comment]
Sgvizler 2.0 works in an HTTPS world. You can test it here : httpS://linkedwiki.com/
If you find a bug, I will fix it.
If you want a new Google visualization, you can add an issue here : https://github.com/BorderCloud/sgvizler2/issues
Bye,
Karima
