### ISSUE TITLE
Consider archiving this repository

### ISSUE THREAD

**Issue by KonradHoeffner** [mgskjaeveland/sgvizler#84]
If I understand this correctly, this project is replaced by <https://github.com/BorderCloud/sgvizler2>. If so, consider closing the issues, adding a link to sgvizler2 and an archival note to the readme file and setting this repository to "archived" in the GitHub project settings so that developers now that we shouldn't file new issues anymore.

**Comment by mgskjaeveland** [comment]
It is not completely correct that the project is replaced by sgvizler2, but this project's code base is used by sgvizler2.

However, since this project is no longer maintained, it makes sense to archive.
